### ISSUE TITLE
aタグなどの属性値を無視したい

### ISSUE THREAD

**Issue by TAKEDA-Takashi** [textlint-rule/textlint-rule-sentence-length#13]
## 概要

aタグなどを文章中に含めた場合、そのaタグの属性値なども文字数としてカウントしてしまい、本来の文章よりも長く判定されてしまう。

## 期待する挙動

タグ自体は無視して、本来のテキスト部分でカウントしてほしい。

## 再現手順

```
$ mkdir test-textlint-maxlength && cd $_ && npm init -y
$ npm install -D textlint textlint-rule-sentence-length
$ cat > .textlintrc <<EOS
{
    "rules": {
        "sentence-length": true
    }
}
EOS

$ cat > index.md <<EOS
ではみなさんは、そういうふうに川だと云いわれたり、乳の流れたあとだと云われたりしていたこのぼんやりと白いものがほんとうは何かご承知ですか。

ではみなさんは、そういうふうに川だと云いわれたり、乳の流れたあとだと云われたりしていたこの<a href="https://www.aozora.gr.jp/cards/000081/files/456_15050.html" target="_blank" rel="noopener noreferrer">ぼんやりと白いもの</a>がほんとうは何かご承知ですか。
EOS

$ npx textlint index.md

/path/to/test-textlint-maxlength/index.md
  3:1  error  Line 3 sentence length(184) exceeds the maximum sentence length of 100.
Over 84 characters  sentence-length

✖ 1 problem (1 error, 0 warnings)
```

**Comment by azu** [comment]
簡単にやるならばHTMLタグ自体を全部無視ですね(おそらく昔の挙動はこれだった)

ちゃんとやるならばら、
https://github.com/textlint/textlint-util-to-string がHTML nodeをそのままHTML文字列として返してしまってるので、この辺でHTMLとして表示したときの文字列(`ぼんやりと白いもの`)をどうにかして取得して返す感じですね。

https://github.com/textlint/textlint-util-to-string/blob/f52e8713e15f29a0b6c37c826fe78dd05603fbbb/src/StringSource.js#L160-L172

- https://github.com/kurttheviking/html2plaintext
- https://www.npmjs.com/package/html-to-text
- https://www.npmjs.com/package/html2plaintext
- https://github.com/kraegpoeth/node-html-to-text2
- https://github.com/rehypejs/rehype-minify/tree/master/packages/hast-util-to-string

**Comment by azu** [comment]
https://github.com/textlint-rule/textlint-rule-sentence-length/releases/tag/2.1.2 で修正してみました。

**Comment by TAKEDA-Takashi** [comment]
修正確認しました！
実際に利用しているのは https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing なのですが、パッケージの更新はbotで自動化しているみたいなので、反映待ってみます。
ありがとうございました！

**Comment by azu** [comment]
patchアップデートなので、`npm update textlint-rule-sentence-length --depth 3` とかで子パッケージのアップデートができるかもしれないですね。(もしくはnpm rmしてnpm install)
